### ISSUE TITLE
(de) MEDIA, HUBS & FORUMS

### ISSUE THREAD

**Issue by ninabreznik** [wizardamigosinstitute/organisation#20]
Find online german customer hubs & influencers (e.g. PR, articles,...)

**Comment by ninabreznik** [comment]
STARTÜBERLIN:
http://www.startuberlin.com/author/steforzan/
http://www.startuberlin.com/author/rosieallabarton/

TECH EU:
http://tech.eu/author/roxanne/

**Comment by ghost** [comment]
Find online german customer hubs & influencers (e.g. PR, articles,...)

**HUBS [Organisations]**
- http://www.jugendnetz-berlin.de/de/medienbildung/methoden_werkzeuge/Programmierung.php
- [ ] **MEDIA [Agents]**
- http://winfuture.de/videos/Software/Trend-Programmieren-fuer-5-Jaehrige-13320.html
- Kleinergast http://kleinerdrei.org/2013/11/coderdojo-berlin-ist-da-der-programmier-club-fur-kids-fand-erstmals-in-berlin-statt/
- Jürgen Stüber http://www.morgenpost.de/berlin-aktuell/startups/article133108028/Kinder-und-Jugendliche-sollen-bei-Code-Week-Programmieren-lernen.html
- SebastianThiele https://www.iamyourfather.de/coderdojo-programmieren-lernen-fuer-kinder
- Farunhofer https://www.fraunhofer.de/de/presse/presseinformationen/2014/November/open-roberta-programmieren-ist-ein-kinderspiel.html
- Johanna Rosenfeld http://www.besonderekinderapps.de/mit-der-schildkrote-das-programmieren-lernen/
- Sandra Rudel http://www.tagesspiegel.de/medien/digitale-welt/programmieren-fuer-kinder-technik-die-begeistert/9587032.html
- Adrian Jagusch http://adrian-jagusch.de/2014/10/apps-programmieren-mit-kindern/
- Lisa Altmeier http://www.zeit.de/digital/internet/2014-05/jugend-hackt-projekt-republica
- [ ] **FORUMS [Channels]**
- Chip forum http://forum.chip.de/programmierung-allgemein/programmieren-fuer-kinder-796947-page3.html
- [ ] **INFLUENCERS [People]**

**Comment by serapath** [comment]
https://otsconfchat.herokuapp.com/
