### ISSUE TITLE
(en) MEDIA, HUBS & FORUMS

### ISSUE THREAD

**Issue by ghost** [wizardamigosinstitute/organisation#4]

**Comment by ninabreznik** [comment]
Wall of inspiration
=====================

This page is our little thank you page for all the communities around us that inspire us to see and follow our vision.


Co.Up is the space where learners and hackers meet Our idea and our community was bort there. Co.Up provides us with space and infrastructure. We are grateful to have them on our side.


Hackidemia crew is dedicated to create new opportunities for children and mentors. They empower entrepreneurial thinking and prepare the next generation of leaders to approach human challenges through creative technical solution. We are hugely inspired by them.

Open tech school  is a movement aiming to offer free tech education. They are designing workshops and awesome learning materials in a welcoming learning environment. Same as them we also want to create new generation of coders and arm them with the new literacy for the future.

Rails Girls organize free workshops for women without prior experience in programming. They are focused into creating an intimate space where questions are welcome and where there is no pressure nor competition. It is a movement for getting more women into tech world and help to close the gender gap in IT. We are grateful and proud to be part of them.


Workation Retreat coconat is a place for digital workers to be inspired, concentrate, work, and play in the countryside. We value their quest for promoting healthy life-work balance and are happy to help them get it ff the ground.

**Comment by ninabreznik** [comment]
HUBS

Toywheel http://toywheel.com/first-kids-hackathon-in-berlin/

Da Vinci http://www.davinci-learning.com/

FastTracKids http://www.fastrackids.com/

The Center (activities in English) http://www.thecenter-berlin.de/workshops-classes-events/

English schools https://webmagazin.de/english/berlin/5-berlin-schools-for-english-speaking-kids-1111000

JustLanded https://www.justlanded.com/

Reddit

MEDIA

Startüberlin
http://www.startuberlin.com/author/steforzan/
http://www.startuberlin.com/author/rosieallabarton/

TechEU
http://tech.eu/author/roxanne/
