### ISSUE TITLE
Wall of Inspiration

### ISSUE THREAD

**Issue by ghost** [wizardamigosinstitute/organisation#41]
> mention: coding amigos, coder dojo, hackedemia, open tech school, rails girls + hacker 
> retreat/hacker ship + mention scholarships at one point (see wall of inspiration)
# Actions

**Comment by ninabreznik** [comment]
- get in touch with all `Wall of Inspiration`
  - `Rails Girls`: can we put "supported/approved by rails girls" (for a rails girl project)
  - `Hacker Retreat`: To prepare next hacker retreat generation for you
  - `Òpen Tech School`: Hack'N'Tell Stefan
  - `Hackidimia`: Stefania
  - `Coder Dojo`: Answer to potsdam
  - `Hackership`: Charlotte
  - Contact `Code Combat`for **Teachers Accounts**
  - `coding amigos`: yes we can!

## Later
- WE make example community page concept (not published!)
- make CC mail to ask them join a gitter chat, later github organisation?
- chat goal: brainstorm about community web page we make for them
