### ISSUE TITLE
Connect to public schools

### ISSUE THREAD

**Issue by ghost** [wizardamigosinstitute/organisation#8]
**Requirements**:
- [ ] `@Update Website`
  - [ ] `Impressum` on Website
  - [ ] `Schedule Section` +8 Scholarships (every quarter)
  - [ ] `Contribute Section` +Info about free Teacher Workshops
- [ ] `@Ask Supporters` to use their names (codecombat, coderdojo, co_up, rails girls, Ministry of Education)

**Start Process**:
- [ ] Email with Letter Announcement
- [ ] Letter to School Directors
- [ ] Call School Directors

**Comment by ninabreznik** [comment]
### Email
- with support from A, B, C we do free workshops for teachers
- We send formal invitation (Letter)
- link to web page

### Letter Content
- with support from A, B, C we do free workshops for teachers
- Available Dates/Location (in 10 days [check holidays]): X, Y, Z or custom
- free `Workshop` for teachers + describe whole application process
- pls setup a call, maybe on Date X + if u want u can  prepare for us going through application process
- or fillout online or attachment of letter
- Footnote: about Institute (offers Scholarships)

**Application**
- Teachers (name, subject, email if they want) or Number of Teachers
- Preferred Date
- Preferred Location
- \+ Link to online form

### Follow Up Email
- Send Link to Online Application Form
- Remind them of telephone call or letter as alternative
  - `Sipgate`answering machine

### Follow Up Call

> Hello, Im calling from Wizardamigos Institute,
> we sent you a letter about free programming workshops for teachers
> Was everything clear, because they are one of the first pilot school that are invited

... free style ...
- go through application process
- or say thank you, next step is ...

### Last Email for rejecters
- give 2 scholarships (2/8) + if more kids want we give Test

### For Accepters
- teach teachers coding resources/games
- mention: coding amigos, coder dojo, hackedemia, open tech school, rails girls + hacker retreat/hacker ship + mention scholarships at one point (see wall of inspiration)
- code combat finishing X levels (then get scholarship)

**Comment by serapath** [comment]
Check https://raw.githubusercontent.com/ini20/berliner-schulen/master/data/data.json
